name: PECalculator.org
description: Public website of pecalculator.org, an open source set of tools for LPs and GPs

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
sass:
  sass_dir: _sass
exclude:
  - CNAME
